// GENERATED by scripts/generate-cli-discovery.ts from lib/discovery/sarif.ts.
// Do not edit here. __tests__/lib/cli-discovery-vendored.test.ts fails if this
// copy and its source disagree, which is what makes them one implementation.
import type { ScanResult } from './scan.js';

/**
 * SARIF 2.1.0 for the discovery scan.
 *
 * WHY SARIF AND NOT A REPORT. GitHub renders SARIF natively in the Security tab
 * and inline on pull requests. Uploading this from the existing GitHub Action
 * puts Article 50 findings where developers already look, with no interface for
 * us to build or them to visit. It is the cheapest distribution surface
 * available to a tool that already runs in CI.
 *
 * EVERYTHING IS A NOTE. SARIF levels are none/note/warning/error, and a scanner
 * that cannot know what you ship has not found an error. `possible` and
 * `likely` are carried in the message instead, so the severity never overstates
 * what a dependency can prove.
 */
export function toSarif(result: ScanResult, toolVersion: string) {
  return {
    $schema: 'https://json.schemastore.org/sarif-2.1.0.json',
    version: '2.1.0',
    runs: [
      {
        tool: {
          driver: {
            name: 'legalithm-discovery',
            version: toolVersion,
            informationUri: 'https://www.legalithm.com/en/tools/ai-discovery-scan',
            rules: result.hypotheses.map((h) => ({
              id: `ai-capability/${h.capability}`,
              name: h.capability,
              shortDescription: { text: `Possible AI capability: ${h.capability}` },
              fullDescription: { text: h.because },
              defaultConfiguration: { level: 'note' },
              help: {
                text:
                  'A hypothesis, not a finding. Confirm whether this capability actually ships before treating any Article 50 duty as applicable.',
              },
            })),
          },
        },
        results: result.hypotheses.flatMap((h) =>
          h.evidence.map((e) => ({
            ruleId: `ai-capability/${h.capability}`,
            level: 'note' as const,
            message: {
              text: `${h.confidence === 'likely' ? 'Likely' : 'Possible'} ${h.capability}: ${h.because} Confirm before relying on it.`,
            },
            locations: [
              {
                physicalLocation: {
                  artifactLocation: { uri: e.file },
                  ...(e.line ? { region: { startLine: e.line } } : {}),
                },
              },
            ],
          })),
        ),
      },
    ],
  };
}
