import { describe, it, expect } from 'vitest';

/**
 * Exercises the VENDORED copy of the record core, through the same import path
 * the published CLI uses.
 *
 * packages/record-core has its own suite, but it imports `../src/`. The CLI
 * ships a copy generated by scripts/generate-cli-record-core.ts, and the only
 * thing asserted about that copy was that its BYTES match the source. Bytes
 * matching is not the same as running: the generator rewrites relative imports
 * to add `.js` for NodeNext, so a mistake there produces a copy that is
 * byte-correct by the drift test and fails to resolve at runtime.
 *
 * This is the test that would catch that, and it is why the vendored files sat
 * at 0% and 2.9% coverage while the identical source sat near 100%.
 */
import {
  canonicalize,
  canonicalJson,
  contentHash,
  shortHash,
  recordHash,
  contentId,
  hypothesisId,
  claimId,
  conflictId,
  isContentId,
  deriveStatus,
  detectConflicts,
  knownAsOf,
  nextVersion,
  verifyChain,
  verifyRecordBundle,
  type Claim,
  type Hypothesis,
} from '../record-core/index.js';

describe('the vendored copy resolves and runs', () => {
  it('verifies a record bundle through the vendored path, offline', () => {
    // This is the exact import path `npx legalithm verify-record --bundle` uses.
    // If the vendored verify.js failed to resolve, this throws; if it drifted
    // from source, the byte-equality test below fails. Together they make
    // "a third party runs the CLI with no network" a proven claim.
    const verdict = verifyRecordBundle({ format: 'not-a-bundle' });
    expect(verdict.ok).toBe(false);
    expect(verdict.reason).toBeTruthy();
  });

  it('re-exports every symbol the CLI relies on', () => {
    for (const fn of [canonicalize, canonicalJson, contentHash, shortHash, recordHash, contentId, isContentId]) {
      expect(typeof fn).toBe('function');
    }
  });

  it('canonicalises identically to the source, Date guard included', () => {
    expect(canonicalJson({ b: 1, a: 2 })).toBe('{"a":2,"b":1}');
    expect(canonicalJson({ d: new Date('2026-01-01T00:00:00.000Z') })).toBe('{"d":"2026-01-01T00:00:00.000Z"}');
  });

  it('mints full-digest ids with a readable prefix', () => {
    const id = hypothesisId({ x: 1 });
    expect(id).toMatch(/^hyp_[0-9a-f]{64}$/);
    expect(isContentId(id)).toBe(true);
    expect(claimId({ x: 1 })).not.toBe(id);
    expect(conflictId({ x: 1 })).toMatch(/^cfl_/);
  });

  it('keeps recordHash blind to volatile stamps', () => {
    expect(recordHash({ a: 1, generatedAt: 'x' })).toBe(recordHash({ a: 1, generatedAt: 'y' }));
    expect(recordHash({ a: 1 })).not.toBe(recordHash({ a: 2 }));
  });

  it('shortHash is a prefix of the full hash', () => {
    const v = { a: 1 };
    expect(contentHash(v).startsWith(shortHash(v))).toBe(true);
  });
});

const claim = (over: Partial<Claim> = {}): Claim =>
  ({
    id: 'clm_1',
    subjectVersionId: 's1',
    surfaceId: null,
    packKey: 'eu-cra',
    obligationRef: 'Annex I (2)(a)',
    assertion: 'met',
    declaredBy: 'Pedram Madani',
    declaredAt: '2026-08-01T00:00:00.000Z',
    observedAt: '2026-08-01T00:00:00.000Z',
    recordedAt: '2026-08-01T00:00:00.000Z',
    ...over,
  }) as Claim;

const hypothesis = (over: Partial<Hypothesis> = {}): Hypothesis =>
  ({
    id: 'hyp_1',
    subjectVersionId: 's1',
    surfaceId: null,
    packKey: 'eu-cra',
    obligationRef: 'Annex I (2)(a)',
    assertion: 'met',
    method: 'automated',
    sourceIdentity: 'scanner@1.0',
    confidence: 'exact',
    observedAt: '2026-08-01T00:00:00.000Z',
    recordedAt: '2026-08-01T00:00:00.000Z',
    ...over,
  }) as Hypothesis;

describe('deriveStatus, through the shipped copy', () => {
  it('is not_assessed with nothing at all', () => {
    expect(deriveStatus([], []).status).toBe('not_assessed');
  });

  it('NEVER lets hypotheses alone produce conformance', () => {
    // The rule the whole architecture rests on.
    const many = Array.from({ length: 50 }, (_, i) => hypothesis({ id: `hyp_${i}` }));
    const r = deriveStatus([], many);
    expect(r.status).toBe('hypothesis_only');
    expect(r.claimIds).toEqual([]);
    expect(r.hypothesisIds).toHaveLength(50);
  });

  it('reports contested when claims disagree, rather than letting the last win', () => {
    const r = deriveStatus([claim(), claim({ id: 'clm_2', assertion: 'not_met' })], []);
    expect(r.status).toBe('contested');
    expect(r.basis).toContain('met vs not_met');
  });

  it('takes the assertion when claims agree', () => {
    expect(deriveStatus([claim(), claim({ id: 'clm_2' })], []).status).toBe('met');
  });

  it('caveats a met claim promoted from an automated hypothesis', () => {
    const r = deriveStatus([claim({ fromHypothesisId: 'hyp_1' })], [hypothesis()]);
    expect(r.status).toBe('met');
    expect(r.caveat).toContain('automated or AI-assisted');
  });

  it('does not caveat when a human produced the hypothesis', () => {
    const r = deriveStatus([claim({ fromHypothesisId: 'hyp_1' })], [hypothesis({ method: 'human_expert' })]);
    expect(r.caveat).toBeNull();
  });

  it('answers as of a past decision time', () => {
    const late = claim({ recordedAt: '2026-09-01T00:00:00.000Z' });
    expect(deriveStatus([late], [], '2026-08-15T00:00:00.000Z').status).toBe('not_assessed');
    expect(deriveStatus([late], [], '2026-09-02T00:00:00.000Z').status).toBe('met');
  });

  it('knownAsOf filters on recordedAt, the learned-at clock', () => {
    const rows = [{ recordedAt: '2026-01-01' }, { recordedAt: '2026-12-01' }];
    expect(knownAsOf(rows, '2026-06-01')).toHaveLength(1);
    expect(knownAsOf(rows)).toHaveLength(2);
  });
});

describe('detectConflicts, through the shipped copy', () => {
  it('finds a disagreement and names both sides', () => {
    const found = detectConflicts([claim(), claim({ id: 'clm_2', assertion: 'not_met' })], '2026-08-15');
    expect(found).toHaveLength(1);
    expect(found[0]!.kind).toBe('claim_disagreement');
    expect([found[0]!.aId, found[0]!.bId].sort()).toEqual(['clm_1', 'clm_2']);
  });

  it('finds none when claims agree', () => {
    expect(detectConflicts([claim(), claim({ id: 'clm_2' })], '2026-08-15')).toEqual([]);
  });

  it('does not cross obligations', () => {
    const other = claim({ id: 'clm_2', assertion: 'not_met', obligationRef: 'Annex I (2)(b)' });
    expect(detectConflicts([claim(), other], '2026-08-15')).toEqual([]);
  });
});

describe('the hash chain, through the shipped copy', () => {
  const input = (n: number) => ({
    subjectId: 's1',
    snapshot: { n },
    packCorpusHashes: { 'eu-cra': 'abc' },
    asOf: '2026-08-15T00:00:00.000Z',
  });

  it('links each version to its predecessor', () => {
    const v1 = nextVersion([], input(1));
    const v2 = nextVersion([v1], input(2));
    expect(v1.n).toBe(1);
    expect(v1.prevSha).toBeNull();
    expect(v2.prevSha).toBe(v1.sha);
    expect(verifyChain([v1, v2])).toEqual({ ok: true, length: 2 });
  });

  it('detects a tampered snapshot', () => {
    const v1 = nextVersion([], input(1));
    const bad = { ...v1, snapshot: { ...v1.snapshot, n: 99 } };
    expect(verifyChain([bad])).toMatchObject({ ok: false, reason: 'snapshot hash mismatch' });
  });

  it('detects a broken link', () => {
    const v1 = nextVersion([], input(1));
    const v2 = nextVersion([v1], input(2));
    expect(verifyChain([v1, { ...v2, prevSha: 'nope' }])).toMatchObject({ ok: false, reason: 'broken prevSha link' });
  });

  it('detects reordering', () => {
    const v1 = nextVersion([], input(1));
    const v2 = nextVersion([v1], input(2));
    expect(verifyChain([v2, v1])).toMatchObject({ ok: false, reason: 'out of order' });
  });

  it('accepts an empty chain', () => {
    expect(verifyChain([])).toEqual({ ok: true, length: 0 });
  });
});
